name: nf_reg_modules CI
# This workflow is triggered on pushes and PRs to the repository.
# It runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on: [push, pull_request]

jobs:
  test_progressive:
    env:
      NXF_VER: '20.07.1'
      NXF_ANSI_LOG: false
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      matrix:
        paramFlavour2run: ["--progressive_align=false --regressive_align=true --slave_align=false --dynamic_align=false --pool_align=false"] 
        paramAlign: [--align_methods=CLUSTALO,--align_methods=MAFFT-FFTNS1,--align_methods=FAMSA]
        paramTreeMethod: ["--tree_methods=MBED,MAFFT-PARTTREE0,MAFFT-DPPARTTREE0,FAMSA-SLINK"]
    steps:
      - uses: actions/checkout@v2
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: Run pipeline with minimal data to check PROGRESSIVE alignments
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test,docker ${{matrix.paramFlavour2run}} ${{matrix.paramAlign}} ${{matrix.paramTreeMethod}}

  test_regressive:
    env:
      NXF_VER: '20.04.1'
      NXF_ANSI_LOG: false
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      matrix:
        paramFlavour2run: ["--progressive_align=false --regressive_align=true --slave_align=false --dynamic_align=false --pool_align=false"] 
        paramAlign: [--align_methods=CLUSTALO,--align_methods=MAFFT-FFTNS1,--align_methods=FAMSA]
        paramTreeMethod: ["--tree_methods=MBED,MAFFT-PARTTREE0,MAFFT-DPPARTTREE0,FAMSA-SLINK"]
        paramBucket: ["--buckets=9,100"]
    steps:
      - uses: actions/checkout@v2
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: Run pipeline with minimal data to check REGRESSIVE alignments
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test,docker ${{matrix.paramFlavour2run}} ${{matrix.paramAlign}} ${{matrix.paramTreeMethod}} ${{matrix.paramBucket}}
  
  test_slave:
    env:
      NXF_VER: '20.04.1'
      NXF_ANSI_LOG: false
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      matrix:
        paramFlavour2run: ["--progressive_align=false --regressive_align=false --slave_align=true --dynamic_align=false --pool_align=false"] 
        paramAlign: [--align_methods=CLUSTALO,--align_methods=MAFFT-FFTNS1,--align_methods=FAMSA]
        paramTreeMethod: ["--tree_methods=MBED,MAFFT-PARTTREE0,MAFFT-DPPARTTREE0,FAMSA-SLINK"]
        paramBucket: ["--buckets=9,100"]
        paramsSlaveTree: ["--slave_tree_methods=mbed,famsadnd,parttree"]
    steps:
      - uses: actions/checkout@v2
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: Run pipeline with minimal data to check SLAVE alignments
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test,docker ${{matrix.paramFlavour2run}} ${{matrix.paramAlign}} ${{matrix.paramTreeMethod}} ${{matrix.paramBucket}} ${{matrix.paramsSlaveTree}}

  test_dynamic:
    env:
      NXF_VER: '20.04.1'
      NXF_ANSI_LOG: false
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      matrix:
        paramFlavour2run: ["--progressive_align=false --regressive_align=false --slave_align=false --dynamic_align=true --pool_align=false"] 
        paramTreeMethod: ["--tree_methods=MBED,MAFFT-PARTTREE0,MAFFT-DPPARTTREE0,FAMSA-SLINK"]
        paramBucket: ["--buckets=10"]
        paramDynamic: ["--dynamicX=10000"]
        paramsConfig: [--dynamicConfig=false,--dynamicConfig=true]
    steps:
      - uses: actions/checkout@v2
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: Run pipeline with minimal data to check REGRESSIVE alignments
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test,docker ${{matrix.paramFlavour2run}} ${{matrix.paramTreeMethod}} ${{matrix.paramBucket}} ${{matrix.paramDynamic}} ${{matrix.paramsConfig}}
          
  test_pool:
    env:
      NXF_VER: '20.04.1'
      NXF_ANSI_LOG: false
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      matrix:
        paramFlavour2run: [--progressive_align=false --regressive_align=false --slave_align=false --dynamic_align=false --pool_align=true] 
        paramAlign: [--align_methods=CLUSTALO,--align_methods=MAFFT-FFTNS1,--align_methods=FAMSA]
        paramTreeMethod: ["--tree_methods=MBED,MAFFT-PARTTREE0,MAFFT-DPPARTTREE0,FAMSA-SLINK"]
        paramBucket: ["--buckets=9,100"] 
    steps:
      - uses: actions/checkout@v2
      - name: Install Nextflow
        run: | 
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: Run pipeline with minimal data to check REGRESSIVE alignments
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test,docker ${{matrix.paramFlavour2run}} ${{matrix.paramAlign}} ${{matrix.paramTreeMethod}} ${{matrix.paramBucket}}
