name: nf_reg_modules CI
# This workflow is triggered on pushes and PRs to the repository.
# It runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on: [push, pull_request]

jobs:
  test_regressive:
     env:
       NXF_VER: '20.01.0'
       NXF_ANSI_LOG: false
     runs-on: ubuntu-latest
     strategy:
       matrix:
         paramFlavour2run: [--progressive_align=false --regressive_align=true --slave_align=false --dynamic_align==false]
         paramAlign: [--align_method=CLUSTALO,--align_method=MAFFT-FFTNS1]
         paramTreeMethod: [--tree_method=MBED,--tree_method=PARTTREE]
     steps:
       - uses: actions/checkout@v2
       - name: Install Nextflow
         run: |
           wget -qO- get.nextflow.io | bash
           sudo mv nextflow /usr/local/bin/
       - name: Run pipeline with minimal data to check REGRESSIVE alignments
         run: |
           nextflow run ${GITHUB_WORKSPACE} -profile test,docker ${{matrix.paramFlavour2run}} ${{matrix.paramAlign}} ${{matrix.paramTreeMethod}}
           
  test_progressive:
     env:
       NXF_VER: '20.01.0'
       NXF_ANSI_LOG: false
     runs-on: ubuntu-latest
     strategy:
       matrix:
         paramFlavour2run: [--progressive_align=true --regressive_align=false --slave_align=false --dynamic_align==false]
         paramAlign: [--align_method=CLUSTALO,--align_method=MAFFT-FFTNS1]
         paramTreeMethod: [--tree_method=MBED,--tree_method=PARTTREE]
     steps:
       - uses: actions/checkout@v2
       - name: Install Nextflow
         run: |
           wget -qO- get.nextflow.io | bash
           sudo mv nextflow /usr/local/bin/
       - name: Run pipeline with minimal data to check PROGRESSIVE alignments
         run: |
           nextflow run ${GITHUB_WORKSPACE} -profile test,docker ${{matrix.paramFlavour2run}} ${{matrix.paramAlign}} ${{matrix.paramTreeMethod}}
           

