name: nf_reg_modules CI
# This workflow is triggered on pushes and PRs to the repository.
# It runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on: [push, pull_request]

jobs:
  test_regressive_CO:
     env:
       NXF_VER: '20.01.0'
       NXF_ANSI_LOG: false
     runs-on: ubuntu-latest
     strategy:
       matrix:
         paramAlign: [--align_method=CLUSTALO]
         paramTreeMethod: [--tree_method=MBED,--tree_method=PARTTREE]
     steps:
       - uses: actions/checkout@v2
       - name: Install Nextflow
         run: |
           wget -qO- get.nextflow.io | bash
           sudo mv nextflow /usr/local/bin/
       - name: Run pipeline with minimal data to check regressive alignments on ClustalO
         run: |
           nextflow run ${GITHUB_WORKSPACE} -profile test,docker ${{ matrix.paramAlign }} ${{ matrix.paramTreeMethod }}
           
  test_regressive_FFTNS1:
     env:
       NXF_VER: '20.01.0'
       NXF_ANSI_LOG: false
     runs-on: ubuntu-latest
     strategy:
       matrix:
         paramAlign: [--align_method=MAFFT-FFTNS1]
         paramTreeMethod: [--tree_method=MBED,--tree_method=PARTTREE]
     steps:
       - uses: actions/checkout@v2
       - name: Install Nextflow
         run: |
           wget -qO- get.nextflow.io | bash
           sudo mv nextflow /usr/local/bin/
       - name: Run pipeline with minimal data to check regressive alignments on Mafft-FFTNS1
         run: |
           nextflow run ${GITHUB_WORKSPACE} -profile test,docker ${{ matrix.paramAlign }} ${{ matrix.paramTreeMethod }}
           

