name: tcoffee CI
# This workflow is triggered on pushes and PRs to the repository.
# It runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on: [push, pull_request]

jobs:
  test_progressive:
    env:
      NXF_VER: '20.04.1'
      NXF_ANSI_LOG: false
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[tc test]')"
    strategy:
      matrix:
        paramsTcMode: ["--progressive_align=false --regressive_align=true --slave_align=false --dynamic_align=false --pool_align=false"] 
    steps:
      - uses: actions/checkout@v2
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: Run pipeline with minimal data to check PROGRESSIVE alignments
        run: |
          nextflow run ${GITHUB_WORKSPACE}/test_tcoffee.nf -profile test,docker ${{matrix.paramsTcMode}}
